/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as BodegasRouteImport } from './routes/bodegas'
import { Route as CadenaRouteImport } from './routes/cadena'
import { Route as CotizadorRouteImport } from './routes/cotizador'
import { Route as CpoRouteImport } from './routes/cpo'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VencimientosRouteImport } from './routes/vencimientos'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners.$partnerId'
import { Route as PartnersNuevoRouteImport } from './routes/partners.nuevo'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProductsNuevoRouteImport } from './routes/products.nuevo'
import { Route as RfqIndexRouteImport } from './routes/rfq.index'
import { Route as RfqRfqIdRouteImport } from './routes/rfq.$rfqId'
import { Route as RfqNuevoRouteImport } from './routes/rfq.nuevo'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesOrderIdRouteImport } from './routes/sales.$orderId'
import { Route as SalesNuevoRouteImport } from './routes/sales.nuevo'
import { Route as SolicitudesIndexRouteImport } from './routes/solicitudes.index'
import { Route as SolicitudesSolicitudIdRouteImport } from './routes/solicitudes.$solicitudId'
import { Route as SolicitudesNuevoRouteImport } from './routes/solicitudes.nuevo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const BodegasRoute = BodegasRouteImport.update({
  id: '/bodegas',
  path: '/bodegas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadenaRoute = CadenaRouteImport.update({
  id: '/cadena',
  path: '/cadena',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizadorRoute = CotizadorRouteImport.update({
  id: '/cotizador',
  path: '/cotizador',
  getParentRoute: () => rootRouteImport,
} as any)
const CpoRoute = CpoRouteImport.update({
  id: '/cpo',
  path: '/cpo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VencimientosRoute = VencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/$partnerId',
  path: '/$partnerId',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersNuevoRoute = PartnersNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => PartnersRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsNuevoRoute = ProductsNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => ProductsRoute,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RfqRoute,
} as any)
const RfqRfqIdRoute = RfqRfqIdRouteImport.update({
  id: '/$rfqId',
  path: '/$rfqId',
  getParentRoute: () => RfqRoute,
} as any)
const RfqNuevoRoute = RfqNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => RfqRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesOrderIdRoute = SalesOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SalesRoute,
} as any)
const SalesNuevoRoute = SalesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => SalesRoute,
} as any)
const SolicitudesIndexRoute = SolicitudesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolicitudesRoute,
} as any)
const SolicitudesSolicitudIdRoute = SolicitudesSolicitudIdRouteImport.update({
  id: '/$solicitudId',
  path: '/$solicitudId',
  getParentRoute: () => SolicitudesRoute,
} as any)
const SolicitudesNuevoRoute = SolicitudesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => SolicitudesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/banks': typeof BanksRoute
  '/bitacora': typeof BitacoraRoute
  '/bodegas': typeof BodegasRoute
  '/cadena': typeof CadenaRoute
  '/cotizador': typeof CotizadorRoute
  '/cpo': typeof CpoRoute
  '/credit': typeof CreditRoute
  '/gastos': typeof GastosRoute
  '/importar': typeof ImportarRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/quotes': typeof QuotesRoute
  '/reportes': typeof ReportesRoute
  '/rfq': typeof RfqRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/solicitudes': typeof SolicitudesRouteWithChildren
  '/statements': typeof StatementsRoute
  '/users': typeof UsersRoute
  '/vencimientos': typeof VencimientosRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/partners/nuevo': typeof PartnersNuevoRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/nuevo': typeof ProductsNuevoRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/nuevo': typeof RfqNuevoRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/sales/nuevo': typeof SalesNuevoRoute
  '/solicitudes/$solicitudId': typeof SolicitudesSolicitudIdRoute
  '/solicitudes/nuevo': typeof SolicitudesNuevoRoute
  '/partners/': typeof PartnersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/solicitudes/': typeof SolicitudesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/banks': typeof BanksRoute
  '/bitacora': typeof BitacoraRoute
  '/bodegas': typeof BodegasRoute
  '/cadena': typeof CadenaRoute
  '/cotizador': typeof CotizadorRoute
  '/cpo': typeof CpoRoute
  '/credit': typeof CreditRoute
  '/gastos': typeof GastosRoute
  '/importar': typeof ImportarRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/quotes': typeof QuotesRoute
  '/reportes': typeof ReportesRoute
  '/settings': typeof SettingsRoute
  '/statements': typeof StatementsRoute
  '/users': typeof UsersRoute
  '/vencimientos': typeof VencimientosRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/partners/nuevo': typeof PartnersNuevoRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/nuevo': typeof ProductsNuevoRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/nuevo': typeof RfqNuevoRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/sales/nuevo': typeof SalesNuevoRoute
  '/solicitudes/$solicitudId': typeof SolicitudesSolicitudIdRoute
  '/solicitudes/nuevo': typeof SolicitudesNuevoRoute
  '/partners': typeof PartnersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/rfq': typeof RfqIndexRoute
  '/sales': typeof SalesIndexRoute
  '/solicitudes': typeof SolicitudesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/banks': typeof BanksRoute
  '/bitacora': typeof BitacoraRoute
  '/bodegas': typeof BodegasRoute
  '/cadena': typeof CadenaRoute
  '/cotizador': typeof CotizadorRoute
  '/cpo': typeof CpoRoute
  '/credit': typeof CreditRoute
  '/gastos': typeof GastosRoute
  '/importar': typeof ImportarRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/purchases': typeof PurchasesRoute
  '/quotes': typeof QuotesRoute
  '/reportes': typeof ReportesRoute
  '/rfq': typeof RfqRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/solicitudes': typeof SolicitudesRouteWithChildren
  '/statements': typeof StatementsRoute
  '/users': typeof UsersRoute
  '/vencimientos': typeof VencimientosRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/partners/nuevo': typeof PartnersNuevoRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/nuevo': typeof ProductsNuevoRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/nuevo': typeof RfqNuevoRoute
  '/sales/$orderId': typeof SalesOrderIdRoute
  '/sales/nuevo': typeof SalesNuevoRoute
  '/solicitudes/$solicitudId': typeof SolicitudesSolicitudIdRoute
  '/solicitudes/nuevo': typeof SolicitudesNuevoRoute
  '/partners/': typeof PartnersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/solicitudes/': typeof SolicitudesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/banks'
    | '/bitacora'
    | '/bodegas'
    | '/cadena'
    | '/cotizador'
    | '/cpo'
    | '/credit'
    | '/gastos'
    | '/importar'
    | '/inventory'
    | '/login'
    | '/partners'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/reportes'
    | '/rfq'
    | '/sales'
    | '/settings'
    | '/solicitudes'
    | '/statements'
    | '/users'
    | '/vencimientos'
    | '/partners/$partnerId'
    | '/partners/nuevo'
    | '/products/$productId'
    | '/products/nuevo'
    | '/rfq/$rfqId'
    | '/rfq/nuevo'
    | '/sales/$orderId'
    | '/sales/nuevo'
    | '/solicitudes/$solicitudId'
    | '/solicitudes/nuevo'
    | '/partners/'
    | '/products/'
    | '/rfq/'
    | '/sales/'
    | '/solicitudes/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/banks'
    | '/bitacora'
    | '/bodegas'
    | '/cadena'
    | '/cotizador'
    | '/cpo'
    | '/credit'
    | '/gastos'
    | '/importar'
    | '/inventory'
    | '/login'
    | '/purchases'
    | '/quotes'
    | '/reportes'
    | '/settings'
    | '/statements'
    | '/users'
    | '/vencimientos'
    | '/partners/$partnerId'
    | '/partners/nuevo'
    | '/products/$productId'
    | '/products/nuevo'
    | '/rfq/$rfqId'
    | '/rfq/nuevo'
    | '/sales/$orderId'
    | '/sales/nuevo'
    | '/solicitudes/$solicitudId'
    | '/solicitudes/nuevo'
    | '/partners'
    | '/products'
    | '/rfq'
    | '/sales'
    | '/solicitudes'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/banks'
    | '/bitacora'
    | '/bodegas'
    | '/cadena'
    | '/cotizador'
    | '/cpo'
    | '/credit'
    | '/gastos'
    | '/importar'
    | '/inventory'
    | '/login'
    | '/partners'
    | '/products'
    | '/purchases'
    | '/quotes'
    | '/reportes'
    | '/rfq'
    | '/sales'
    | '/settings'
    | '/solicitudes'
    | '/statements'
    | '/users'
    | '/vencimientos'
    | '/partners/$partnerId'
    | '/partners/nuevo'
    | '/products/$productId'
    | '/products/nuevo'
    | '/rfq/$rfqId'
    | '/rfq/nuevo'
    | '/sales/$orderId'
    | '/sales/nuevo'
    | '/solicitudes/$solicitudId'
    | '/solicitudes/nuevo'
    | '/partners/'
    | '/products/'
    | '/rfq/'
    | '/sales/'
    | '/solicitudes/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  BanksRoute: typeof BanksRoute
  BitacoraRoute: typeof BitacoraRoute
  BodegasRoute: typeof BodegasRoute
  CadenaRoute: typeof CadenaRoute
  CotizadorRoute: typeof CotizadorRoute
  CpoRoute: typeof CpoRoute
  CreditRoute: typeof CreditRoute
  GastosRoute: typeof GastosRoute
  ImportarRoute: typeof ImportarRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  PurchasesRoute: typeof PurchasesRoute
  QuotesRoute: typeof QuotesRoute
  ReportesRoute: typeof ReportesRoute
  RfqRoute: typeof RfqRouteWithChildren
  SalesRoute: typeof SalesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SolicitudesRoute: typeof SolicitudesRouteWithChildren
  StatementsRoute: typeof StatementsRoute
  UsersRoute: typeof UsersRoute
  VencimientosRoute: typeof VencimientosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodegas': {
      id: '/bodegas'
      path: '/bodegas'
      fullPath: '/bodegas'
      preLoaderRoute: typeof BodegasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadena': {
      id: '/cadena'
      path: '/cadena'
      fullPath: '/cadena'
      preLoaderRoute: typeof CadenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizador': {
      id: '/cotizador'
      path: '/cotizador'
      fullPath: '/cotizador'
      preLoaderRoute: typeof CotizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpo': {
      id: '/cpo'
      path: '/cpo'
      fullPath: '/cpo'
      preLoaderRoute: typeof CpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vencimientos': {
      id: '/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof VencimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/nuevo': {
      id: '/partners/nuevo'
      path: '/nuevo'
      fullPath: '/partners/nuevo'
      preLoaderRoute: typeof PartnersNuevoRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/nuevo': {
      id: '/products/nuevo'
      path: '/nuevo'
      fullPath: '/products/nuevo'
      preLoaderRoute: typeof ProductsNuevoRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof RfqRoute
    }
    '/rfq/$rfqId': {
      id: '/rfq/$rfqId'
      path: '/$rfqId'
      fullPath: '/rfq/$rfqId'
      preLoaderRoute: typeof RfqRfqIdRouteImport
      parentRoute: typeof RfqRoute
    }
    '/rfq/nuevo': {
      id: '/rfq/nuevo'
      path: '/nuevo'
      fullPath: '/rfq/nuevo'
      preLoaderRoute: typeof RfqNuevoRouteImport
      parentRoute: typeof RfqRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/$orderId': {
      id: '/sales/$orderId'
      path: '/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof SalesOrderIdRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/nuevo': {
      id: '/sales/nuevo'
      path: '/nuevo'
      fullPath: '/sales/nuevo'
      preLoaderRoute: typeof SalesNuevoRouteImport
      parentRoute: typeof SalesRoute
    }
    '/solicitudes/': {
      id: '/solicitudes/'
      path: '/'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof SolicitudesIndexRouteImport
      parentRoute: typeof SolicitudesRoute
    }
    '/solicitudes/$solicitudId': {
      id: '/solicitudes/$solicitudId'
      path: '/$solicitudId'
      fullPath: '/solicitudes/$solicitudId'
      preLoaderRoute: typeof SolicitudesSolicitudIdRouteImport
      parentRoute: typeof SolicitudesRoute
    }
    '/solicitudes/nuevo': {
      id: '/solicitudes/nuevo'
      path: '/nuevo'
      fullPath: '/solicitudes/nuevo'
      preLoaderRoute: typeof SolicitudesNuevoRouteImport
      parentRoute: typeof SolicitudesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnersRouteChildren {
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRoute
  PartnersNuevoRoute: typeof PartnersNuevoRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersPartnerIdRoute: PartnersPartnerIdRoute,
  PartnersNuevoRoute: PartnersNuevoRoute,
  PartnersIndexRoute: PartnersIndexRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNuevoRoute: typeof ProductsNuevoRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNuevoRoute: ProductsNuevoRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface RfqRouteChildren {
  RfqRfqIdRoute: typeof RfqRfqIdRoute
  RfqNuevoRoute: typeof RfqNuevoRoute
  RfqIndexRoute: typeof RfqIndexRoute
}

const RfqRouteChildren: RfqRouteChildren = {
  RfqRfqIdRoute: RfqRfqIdRoute,
  RfqNuevoRoute: RfqNuevoRoute,
  RfqIndexRoute: RfqIndexRoute,
}

const RfqRouteWithChildren = RfqRoute._addFileChildren(RfqRouteChildren)

interface SalesRouteChildren {
  SalesOrderIdRoute: typeof SalesOrderIdRoute
  SalesNuevoRoute: typeof SalesNuevoRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesOrderIdRoute: SalesOrderIdRoute,
  SalesNuevoRoute: SalesNuevoRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface SolicitudesRouteChildren {
  SolicitudesSolicitudIdRoute: typeof SolicitudesSolicitudIdRoute
  SolicitudesNuevoRoute: typeof SolicitudesNuevoRoute
  SolicitudesIndexRoute: typeof SolicitudesIndexRoute
}

const SolicitudesRouteChildren: SolicitudesRouteChildren = {
  SolicitudesSolicitudIdRoute: SolicitudesSolicitudIdRoute,
  SolicitudesNuevoRoute: SolicitudesNuevoRoute,
  SolicitudesIndexRoute: SolicitudesIndexRoute,
}

const SolicitudesRouteWithChildren = SolicitudesRoute._addFileChildren(
  SolicitudesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  BanksRoute: BanksRoute,
  BitacoraRoute: BitacoraRoute,
  BodegasRoute: BodegasRoute,
  CadenaRoute: CadenaRoute,
  CotizadorRoute: CotizadorRoute,
  CpoRoute: CpoRoute,
  CreditRoute: CreditRoute,
  GastosRoute: GastosRoute,
  ImportarRoute: ImportarRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  PurchasesRoute: PurchasesRoute,
  QuotesRoute: QuotesRoute,
  ReportesRoute: ReportesRoute,
  RfqRoute: RfqRouteWithChildren,
  SalesRoute: SalesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SolicitudesRoute: SolicitudesRouteWithChildren,
  StatementsRoute: StatementsRoute,
  UsersRoute: UsersRoute,
  VencimientosRoute: VencimientosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
